version: "3"

services:
  frontend:
    image: doctorpok/whatsup:frontend
    container_name: frontend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    image: doctorpok/whatsup:backend
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
